info:
  contact: {}
paths:
  /backlog/addBacklog:
    post:
      consumes:
      - application/json
      description: do ping
      parameters:
      - description: backlogText
        in: query
        name: backlogText
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 新增待办信息
      tags:
      - 用户相关方法
  /backlog/changeBackStatus:
    get:
      consumes:
      - application/json
      description: |-
        { BacklogStatus: 0/1/2/3/4 } 已删除 0 正常显示1 轻度紧急2 中度紧急3 非常紧急4
        { BacklogType: 1/2 } 正在待办1,已完成2
      parameters:
      - description: backlog_type
        in: query
        name: backlog_type
        required: true
        type: string
      - description: backlog_status
        in: query
        name: backlog_status
        required: true
        type: string
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 删除/置为已完成/置为未完成
      tags:
      - 用户相关方法
  /backlog/getBacklogList:
    get:
      consumes:
      - application/json
      description: '{ backlog_type: 1/2 } 1 正在待办  2 已经完成(有效期1个月内的，按照创建时间获取)'
      parameters:
      - description: backlog_type
        in: query
        name: backlog_type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 获取待办信息列表
      tags:
      - 用户相关方法
  /list/addUserResume:
    post:
      consumes:
      - application/json
      description: |-
        do ping
        /list/addUserResume
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      - description: email
        in: query
        name: email
        required: true
        type: string
      - description: resumeUrl
        in: query
        name: resumeUrl
        required: true
        type: string
      - description: phone
        in: query
        name: phone
        type: string
      - description: gender
        in: query
        name: gender
        type: string
      - description: employmentIntention
        in: query
        name: employmentIntention
        type: string
      - description: confirmEnrollment
        in: query
        name: confirmEnrollment
        type: string
      - description: jobbed
        in: query
        name: jobbed
        type: string
      - description: level
        in: query
        name: level
        type: string
      - description: targetCompany
        in: query
        name: targetCompany
        type: string
      - description: postSalary
        in: query
        name: postSalary
        type: string
      - description: timeInduction
        in: query
        name: timeInduction
        type: string
      - description: firstContactTime
        in: query
        name: firstContactTime
        type: string
      - description: personCharge
        in: query
        name: personCharge
        type: string
      - description: remarks
        in: query
        name: remarks
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 添加简历
      tags:
      - 简历方法
  /list/delete:
    get:
      consumes:
      - application/json
      description: |-
        { id: 1}
        url: /list/detail
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 删除简历
      tags:
      - 简历方法
  /list/deleted:
    get:
      consumes:
      - application/json
      description: 'url: /list/deleted'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 获取已经删除的个人信息
      tags:
      - 管理员(admin)方法
  /list/detail:
    get:
      consumes:
      - application/json
      description: |-
        { id: 1}
        url: /list/detail
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 简历详情
      tags:
      - 简历方法
  /list/mainResume:
    get:
      consumes:
      - application/json
      description: '{ "page": 1, "pageSize": 10 }'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 获取重点关注人群简历列表接口
      tags:
      - 简历方法
  /list/modifyMain:
    post:
      consumes:
      - application/json
      description: '{"status":0, id: 1}'
      parameters:
      - description: true/false
        in: query
        name: status
        required: true
        type: string
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 取消/添加重点标记 false取消 true 添加
      tags:
      - 简历方法
  /list/resume:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 获取简历列表接口
      tags:
      - 简历方法
  /list/updateInfo:
    post:
      consumes:
      - application/json
      description: 'url: /list/updateInfo'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 修改简历库个人信息
      tags:
      - 简历方法
  /list/upload:
    post:
      consumes:
      - application/json
      description: /list/upload
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 上传文件
      tags:
      - 公共方法
  /login:
    post:
      consumes:
      - application/json
      description: do ping
      parameters:
      - description: email
        in: query
        name: email
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 公共方法
  /refreshToken:
    get:
      consumes:
      - application/json
      description: do ping
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 验证token
      tags:
      - 公共方法
  /register:
    post:
      consumes:
      - application/json
      description: do ping
      parameters:
      - description: email
        in: query
        name: email
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      - description: code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 用户注册
      tags:
      - 公共方法
  /sendMail:
    post:
      description: do ping
      parameters:
      - description: email
        in: query
        name: email
        required: true
        type: string
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 邮箱获取验证码
      tags:
      - 公共方法
  /user/addUser:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 管理员手动添加用户
      tags:
      - 管理员(admin)方法
  /user/addUserInfo:
    post:
      consumes:
      - application/json
      description: /user/addUserInfo
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 添加用户/修改用户信息
      tags:
      - 用户相关方法
  /user/userList:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 获取系统内所有的用户
      tags:
      - 管理员(admin)方法
  /user/userinfo:
    get:
      consumes:
      - application/json
      description: /user/userinfo
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":"200", "message":"", "data":""}'
          schema:
            type: string
      summary: 获取用户信息
      tags:
      - 用户相关方法
swagger: "2.0"
